config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(set_task)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
  end

  def update
    @task.update(set_task)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def set_task
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<script src="https://kit.fontawesome.com/ec53cf1278.js" crossorigin="anonymous"></script>
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :completed %>
  <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<script src="https://kit.fontawesome.com/ec53cf1278.js" crossorigin="anonymous"></script>
<div class="container">
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
  <div class="d-flex align-items-end">
    <div class="row ">
  <h3>
    <% if task.completed %>
      <i class="far fa-check-square"></i>
    <% else %>
      <i class="far fa-square"></i>
    <% end %>
    <%= link_to task_path(task) do %>
      <%= task.title.capitalize %>
    <% end %>
  </h3>
  <p><%= link_to delete_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
     <i class="far fa-trash-alt">Delete</i>
      <%=  %>
     <% end %>
  </p>
  </div>
  </div>
<% end %>

<h3><%= link_to "Create a new task", new_path %></h3>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<script src="https://kit.fontawesome.com/ec53cf1278.js" crossorigin="anonymous"></script>

<div class="container">
<div class="d-flex justify-content-between">
  <div class="row align-items-center ">
    <h1><%= @task.title.capitalize %></h1>
    <h5><%= link_to "Edit this task", edit_path %></h5>
  </div>
</div>
<p class="details"><%= @task.details.capitalize %></p>
<% if @task.completed %>
  <p><i class="far fa-check-square"></i> This task is completed.</p>
<% else %>
  <p><i class="far fa-square"></i> This task is not completed.</p>
<% end %>

<h4><%= link_to "Back", tasks_path %></h4>
</div>